db:
  hostname: localhost
  port: 3306
  dbname: nntp_reader_java
  username: root
  password:
credentials:
  hostname: free.xsusenet.com
  port: 80
  username: 113314620348
  password: d9O89xYq7z
  workerCount: 5
groups:
 - alt.binaries.machnur